
package Interfaces;
import java.util.ArrayList;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.HashSet;
import java.util.Set;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.border.Border;

/**
 *
 * @author alver
 */
public class Dashboard extends javax.swing.JFrame {
    JLabel[] menuOpciones = new JLabel[6];  
    JPanel[] menuPaneles = new JPanel[6];
    
    public Dashboard() {
        initComponents();
        this.setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/Tekli icon.png")).getImage());
        
        Border panelBorder = BorderFactory.createMatteBorder(0, 0, 2, 0, Color.lightGray);
        // panel container border
        Border containerBorder = BorderFactory.createMatteBorder(1, 1, 1, 1, new Color(46,49,49));
        
        this.pnlEstudioDespl.setVisible(false);
        this.pnlNotasDespl.setVisible(false);
        this.pnlInfoDespl.setVisible(false);
        this.pnlCalendarioDespl.setVisible(false);
        this.pnlRelojPDespl.setVisible(false);
        
        
        this.pnlTablero.setBackground(new Color(52,89,239));
        this.pnlTablero.setForeground(Color.white);
        
        //Construimos un array a partir de las opciones en el panel izquierdo
        menuOpciones[0] = this.pnlTablero;
        menuOpciones[1] = this.pnlEstudio;
        menuOpciones[2] = this.pnlNotas;
        menuOpciones[3] = this.pnlInfo;
        menuOpciones[4] = this.pnlCalendario;
        menuOpciones[5] = this.pnlRelojP;
        
        //Construimos un array a partir de los paneles que hay en el panel izquierdo
        menuPaneles[0] = this.pnlTableroDespl;
        menuPaneles[1] = this.pnlEstudioDespl;
        menuPaneles[2] = this.pnlNotasDespl;
        menuPaneles[3] = this.pnlInfoDespl;
        menuPaneles[4] = this.pnlCalendarioDespl;
        menuPaneles[5] = this.pnlRelojPDespl;
        
        AñadirAccionesMenu();
    }
    Border defaultBorder = BorderFactory.createMatteBorder(1, 0, 1, 0, new Color(255,255,255));
     
    Border blueBorder = BorderFactory.createMatteBorder(1, 0, 1, 0, new Color(52,89,239));
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void setFondoOpcion(JLabel label)
    {   
        //reinicia los colores de la opción
        for(JLabel a: menuOpciones)
        {
           a.setBackground(Color.white);
           a.setForeground(Color.black);
        }
        //Cambia el color del fondo de la opción al azul escogido
        label.setBackground(new Color(52,89,239));
        //Cambia el color de las letras de la opción a blanco
        label.setForeground(Color.white);
        
    }
    
    public void showPanel(JPanel panel)
    {
        //Esto oculta cada uno de los paneles
        for(JPanel b:menuPaneles)
        {
            b.setVisible(false);
        }
        //Muestra el panel seleccionado
        panel.setVisible(true);
    }
    
    public void AñadirAccionesMenu()
    {
        Component []  components = pnlIzq.getComponents();
        
        for(Component component : components)
        {
            if(component instanceof JLabel)
            {
                JLabel label = (JLabel) component;
                
                label.addMouseListener(new MouseListener() {
                    @Override
                    public void mouseClicked(MouseEvent e) {
                        //Torna el color del la opción de color azul
                        setFondoOpcion(label);
                        
                        //Desplega la opción seleccionada
                        switch (label.getText().trim())
                        {
                            case "Tablero":
                                showPanel(pnlTableroDespl);
                            break;
                            
                            case "Estudio":
                                showPanel(pnlEstudioDespl);
                            break;
                            
                            case "Información":
                                showPanel(pnlInfoDespl);
                            break;
                            
                            case "Notas":
                                showPanel(pnlNotasDespl);
                            break;
                            
                            case "Calendario":
                                showPanel(pnlCalendarioDespl);
                            break;
                            
                            case "RelojPomodoro":
                                    showPanel(pnlRelojPDespl);
                            break;
                        }
                        
                    }

                    @Override
                    public void mousePressed(MouseEvent e) {

                    }

                    @Override
                    public void mouseReleased(MouseEvent e) {
                        
                    }

                    @Override
                    public void mouseEntered(MouseEvent e) {
                        label.setBorder(blueBorder);
                        //Colorea el borde de azúl
                        
                    }

                    @Override
                    public void mouseExited(MouseEvent e) {
                        //Reinicia el borde
                        label.setBorder(defaultBorder);
                    }
                });
        }
    }
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlIzq = new javax.swing.JPanel();
        pnlRelojP = new javax.swing.JLabel();
        pnlTablero = new javax.swing.JLabel();
        pnlEstudio = new javax.swing.JLabel();
        pnlNotas = new javax.swing.JLabel();
        pnlInfo = new javax.swing.JLabel();
        pnlCalendario = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        pnlTableroDespl = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pnlEstudioDespl = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        pnlNotasDespl = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        pnlInfoDespl = new javax.swing.JPanel();
        informacion = new javax.swing.JLabel();
        pnlCalendarioDespl = new javax.swing.JPanel();
        informacion1 = new javax.swing.JLabel();
        pnlRelojPDespl = new javax.swing.JPanel();
        informacion2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        pnlIzq.setBackground(new java.awt.Color(255, 255, 255));
        pnlIzq.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlRelojP.setBackground(new java.awt.Color(255, 255, 255));
        pnlRelojP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pnlRelojP.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pnlRelojP.setText("    Reloj Pomodoro");
        pnlRelojP.setOpaque(true);
        pnlIzq.add(pnlRelojP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 386, 260, 50));

        pnlTablero.setBackground(new java.awt.Color(255, 255, 255));
        pnlTablero.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pnlTablero.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pnlTablero.setText("    Tablero");
        pnlTablero.setOpaque(true);
        pnlIzq.add(pnlTablero, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 106, 260, 50));

        pnlEstudio.setBackground(new java.awt.Color(255, 255, 255));
        pnlEstudio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pnlEstudio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pnlEstudio.setText("    Estudio");
        pnlEstudio.setOpaque(true);
        pnlIzq.add(pnlEstudio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 162, 260, 50));

        pnlNotas.setBackground(new java.awt.Color(255, 255, 255));
        pnlNotas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pnlNotas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pnlNotas.setText("    Notas");
        pnlNotas.setOpaque(true);
        pnlIzq.add(pnlNotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 218, 260, 50));

        pnlInfo.setBackground(new java.awt.Color(255, 255, 255));
        pnlInfo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pnlInfo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pnlInfo.setText("    Información");
        pnlInfo.setOpaque(true);
        pnlIzq.add(pnlInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 274, 260, 50));

        pnlCalendario.setBackground(new java.awt.Color(255, 255, 255));
        pnlCalendario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pnlCalendario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pnlCalendario.setText("    Calendario");
        pnlCalendario.setOpaque(true);
        pnlIzq.add(pnlCalendario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 260, 50));

        jLabel33.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Tekli icon.png"))); // NOI18N
        jLabel33.setText(" Cuenta");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlIzq.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, -1));

        jPanel2.setBackground(new java.awt.Color(52, 89, 239));

        pnlTableroDespl.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Tiempo");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 302, 47));

        jLabel5.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        jLabel5.setText("<html>Aquí aparecerá información sobre el tiempo que haz estado en la aplicación</html>");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 260, 50));

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Tarjetas");
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 302, 47));

        jLabel7.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        jLabel7.setText("<html>Aquí aparecerá información sobre tus tarjetas</html>");
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 260, 50));

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Calendario");
        jPanel7.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 302, 47));

        jLabel9.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        jLabel9.setText("<html> Aquí aparecerán los siguientes eventos en tu calendario</html>");
        jPanel7.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 260, 50));

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Datos");
        jPanel8.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 302, 47));

        jLabel11.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        jLabel11.setText("<html> Aquí aparecerá información sobre datos enfocados en el aprendizajes de ambitos como la psicología o la neurología</html>");
        jPanel8.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 260, 90));

        javax.swing.GroupLayout pnlTableroDesplLayout = new javax.swing.GroupLayout(pnlTableroDespl);
        pnlTableroDespl.setLayout(pnlTableroDesplLayout);
        pnlTableroDesplLayout.setHorizontalGroup(
            pnlTableroDesplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTableroDesplLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(pnlTableroDesplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlTableroDesplLayout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlTableroDesplLayout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        pnlTableroDesplLayout.setVerticalGroup(
            pnlTableroDesplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTableroDesplLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(pnlTableroDesplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(pnlTableroDesplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE))
                .addGap(61, 61, 61))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_multiplyblue_32.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(9, 9, 9))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(5, 5, 5))
        );

        pnlEstudioDespl.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/SesionGrande.png"))); // NOI18N
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 250, 230));

        jLabel18.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Sesion de estudio");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 290, 40));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Gestionar.png"))); // NOI18N
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 250, 230));

        jLabel20.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Gestionar Tarjetas");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 270, 56));

        javax.swing.GroupLayout pnlEstudioDesplLayout = new javax.swing.GroupLayout(pnlEstudioDespl);
        pnlEstudioDespl.setLayout(pnlEstudioDesplLayout);
        pnlEstudioDesplLayout.setHorizontalGroup(
            pnlEstudioDesplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEstudioDesplLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );
        pnlEstudioDesplLayout.setVerticalGroup(
            pnlEstudioDesplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEstudioDesplLayout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addGroup(pnlEstudioDesplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEstudioDesplLayout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlEstudioDesplLayout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
                        .addGap(107, 107, 107))))
        );

        jLabel14.setFont(new java.awt.Font("Segoe UI Light", 0, 48)); // NOI18N
        jLabel14.setText("Notas");

        javax.swing.GroupLayout pnlNotasDesplLayout = new javax.swing.GroupLayout(pnlNotasDespl);
        pnlNotasDespl.setLayout(pnlNotasDesplLayout);
        pnlNotasDesplLayout.setHorizontalGroup(
            pnlNotasDesplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 814, Short.MAX_VALUE)
            .addGroup(pnlNotasDesplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlNotasDesplLayout.createSequentialGroup()
                    .addGap(219, 219, 219)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(245, Short.MAX_VALUE)))
        );
        pnlNotasDesplLayout.setVerticalGroup(
            pnlNotasDesplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 587, Short.MAX_VALUE)
            .addGroup(pnlNotasDesplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlNotasDesplLayout.createSequentialGroup()
                    .addGap(228, 228, 228)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(207, Short.MAX_VALUE)))
        );

        informacion.setFont(new java.awt.Font("Segoe UI Light", 0, 48)); // NOI18N
        informacion.setText("Informacion");

        javax.swing.GroupLayout pnlInfoDesplLayout = new javax.swing.GroupLayout(pnlInfoDespl);
        pnlInfoDespl.setLayout(pnlInfoDesplLayout);
        pnlInfoDesplLayout.setHorizontalGroup(
            pnlInfoDesplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 814, Short.MAX_VALUE)
            .addGroup(pnlInfoDesplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlInfoDesplLayout.createSequentialGroup()
                    .addGap(219, 219, 219)
                    .addComponent(informacion, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(245, Short.MAX_VALUE)))
        );
        pnlInfoDesplLayout.setVerticalGroup(
            pnlInfoDesplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 587, Short.MAX_VALUE)
            .addGroup(pnlInfoDesplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlInfoDesplLayout.createSequentialGroup()
                    .addGap(228, 228, 228)
                    .addComponent(informacion, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(207, Short.MAX_VALUE)))
        );

        informacion1.setFont(new java.awt.Font("Segoe UI Light", 0, 48)); // NOI18N
        informacion1.setText("Calendario");

        javax.swing.GroupLayout pnlCalendarioDesplLayout = new javax.swing.GroupLayout(pnlCalendarioDespl);
        pnlCalendarioDespl.setLayout(pnlCalendarioDesplLayout);
        pnlCalendarioDesplLayout.setHorizontalGroup(
            pnlCalendarioDesplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 814, Short.MAX_VALUE)
            .addGroup(pnlCalendarioDesplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlCalendarioDesplLayout.createSequentialGroup()
                    .addGap(219, 219, 219)
                    .addComponent(informacion1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(245, Short.MAX_VALUE)))
        );
        pnlCalendarioDesplLayout.setVerticalGroup(
            pnlCalendarioDesplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 587, Short.MAX_VALUE)
            .addGroup(pnlCalendarioDesplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlCalendarioDesplLayout.createSequentialGroup()
                    .addGap(228, 228, 228)
                    .addComponent(informacion1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(207, Short.MAX_VALUE)))
        );

        informacion2.setFont(new java.awt.Font("Segoe UI Light", 0, 48)); // NOI18N
        informacion2.setText("Reloj Pomodoro");

        javax.swing.GroupLayout pnlRelojPDesplLayout = new javax.swing.GroupLayout(pnlRelojPDespl);
        pnlRelojPDespl.setLayout(pnlRelojPDesplLayout);
        pnlRelojPDesplLayout.setHorizontalGroup(
            pnlRelojPDesplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 814, Short.MAX_VALUE)
            .addGroup(pnlRelojPDesplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlRelojPDesplLayout.createSequentialGroup()
                    .addGap(219, 219, 219)
                    .addComponent(informacion2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(245, Short.MAX_VALUE)))
        );
        pnlRelojPDesplLayout.setVerticalGroup(
            pnlRelojPDesplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 587, Short.MAX_VALUE)
            .addGroup(pnlRelojPDesplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlRelojPDesplLayout.createSequentialGroup()
                    .addGap(228, 228, 228)
                    .addComponent(informacion2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(207, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlTableroDespl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlEstudioDespl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlNotasDespl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlInfoDespl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlCalendarioDespl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlRelojPDespl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlTableroDespl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(4, 4, 4))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(60, Short.MAX_VALUE)
                    .addComponent(pnlEstudioDespl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(60, Short.MAX_VALUE)
                    .addComponent(pnlNotasDespl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(60, Short.MAX_VALUE)
                    .addComponent(pnlInfoDespl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(60, Short.MAX_VALUE)
                    .addComponent(pnlCalendarioDespl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(60, Short.MAX_VALUE)
                    .addComponent(pnlRelojPDespl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlIzq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pnlIzq, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        
    }//GEN-LAST:event_jPanel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel informacion;
    private javax.swing.JLabel informacion1;
    private javax.swing.JLabel informacion2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel pnlCalendario;
    private javax.swing.JPanel pnlCalendarioDespl;
    private javax.swing.JLabel pnlEstudio;
    private javax.swing.JPanel pnlEstudioDespl;
    private javax.swing.JLabel pnlInfo;
    private javax.swing.JPanel pnlInfoDespl;
    private javax.swing.JPanel pnlIzq;
    private javax.swing.JLabel pnlNotas;
    private javax.swing.JPanel pnlNotasDespl;
    private javax.swing.JLabel pnlRelojP;
    private javax.swing.JPanel pnlRelojPDespl;
    private javax.swing.JLabel pnlTablero;
    private javax.swing.JPanel pnlTableroDespl;
    // End of variables declaration//GEN-END:variables
}
